export const US_MED_SCHOOLS = [
  // ── MD (LCME) ──
  {name:"University of Alabama at Birmingham School of Medicine"},
  {name:"University of South Alabama Frederick P. Whiddon College of Medicine"},
  {name:"University of Arizona College of Medicine – Tucson"},
  {name:"University of Arizona College of Medicine – Phoenix"},
  {name:"Alice L. Walton School of Medicine"},
  {name:"University of Arkansas for Medical Sciences College of Medicine"},
  {name:"California Northstate University College of Medicine"},
  {name:"California University of Science and Medicine"},
  {name:"Charles R. Drew University of Medicine and Science College of Medicine"},
  {name:"Kaiser Permanente Bernard J. Tyson School of Medicine"},
  {name:"University of Southern California Keck School of Medicine"},
  {name:"Loma Linda University School of Medicine"},
  {name:"Stanford University School of Medicine"},
  {name:"University of California, Davis School of Medicine"},
  {name:"University of California, Irvine School of Medicine"},
  {name:"University of California, Riverside School of Medicine"},
  {name:"University of California, San Diego School of Medicine"},
  {name:"University of California, San Francisco School of Medicine"},
  {name:"University of California, Los Angeles David Geffen School of Medicine"},
  {name:"University of Colorado School of Medicine", campuses:["Aurora (Anschutz), CO","Colorado Springs, CO","Fort Collins, CO"]},
  {name:"University of Connecticut School of Medicine"},
  {name:"Quinnipiac University Frank H. Netter MD School of Medicine"},
  {name:"Yale School of Medicine"},
  {name:"George Washington University School of Medicine & Health Sciences"},
  {name:"Georgetown University School of Medicine"},
  {name:"Howard University College of Medicine"},
  {name:"Florida International University Herbert Wertheim College of Medicine"},
  {name:"University of Florida College of Medicine"},
  {name:"Florida Atlantic University Charles E. Schmidt College of Medicine"},
  {name:"Florida State University College of Medicine"},
  {name:"University of Miami Miller School of Medicine"},
  {name:"Nova Southeastern University Dr. Kiran C. Patel College of Allopathic Medicine"},
  {name:"University of Central Florida College of Medicine"},
  {name:"University of South Florida Morsani College of Medicine"},
  {name:"Emory University School of Medicine"},
  {name:"Augusta University Medical College of Georgia"},
  {name:"Mercer University School of Medicine", campuses:["Macon, GA","Savannah, GA","Columbus, GA"]},
  {name:"Morehouse School of Medicine"},
  {name:"University of Hawaiʻi at Mānoa John A. Burns School of Medicine"},
  {name:"Carle Illinois College of Medicine"},
  {name:"Rosalind Franklin University Chicago Medical School"},
  {name:"University of Chicago Pritzker School of Medicine"},
  {name:"University of Illinois College of Medicine", campuses:["Chicago, IL","Peoria, IL","Rockford, IL"]},
  {name:"Loyola University Chicago Stritch School of Medicine"},
  {name:"Northwestern University Feinberg School of Medicine"},
  {name:"Rush Medical College"},
  {name:"Southern Illinois University School of Medicine"},
  {name:"Indiana University School of Medicine", campuses:["Indianapolis, IN","Bloomington, IN","Evansville, IN","Fort Wayne, IN","Gary (Northwest), IN","Muncie, IN","South Bend, IN","Terre Haute, IN","West Lafayette, IN"]},
  {name:"University of Iowa Carver College of Medicine"},
  {name:"University of Kansas School of Medicine", campuses:["Kansas City, KS","Wichita, KS","Salina, KS"]},
  {name:"University of Kentucky College of Medicine"},
  {name:"University of Louisville School of Medicine"},
  {name:"LSU Health New Orleans School of Medicine"},
  {name:"LSU Health Shreveport School of Medicine"},
  {name:"Tulane University School of Medicine"},
  {name:"Johns Hopkins School of Medicine"},
  {name:"University of Maryland School of Medicine"},
  {name:"Uniformed Services University F. Edward Hébert School of Medicine"},
  {name:"Boston University Chobanian & Avedisian School of Medicine"},
  {name:"Harvard Medical School"},
  {name:"University of Massachusetts Chan Medical School"},
  {name:"Tufts University School of Medicine"},
  {name:"Central Michigan University College of Medicine"},
  {name:"University of Michigan Medical School"},
  {name:"Michigan State University College of Human Medicine", campuses:["East Lansing, MI","Grand Rapids, MI"]},
  {name:"Oakland University William Beaumont School of Medicine"},
  {name:"Wayne State University School of Medicine"},
  {name:"Western Michigan University Homer Stryker M.D. School of Medicine"},
  {name:"Mayo Clinic Alix School of Medicine"},
  {name:"University of Minnesota Medical School"},
  {name:"University of Missouri School of Medicine"},
  {name:"University of Missouri–Kansas City School of Medicine"},
  {name:"Saint Louis University School of Medicine"},
  {name:"Washington University School of Medicine"},
  {name:"University of Mississippi School of Medicine"},
  {name:"Creighton University School of Medicine"},
  {name:"University of Nebraska Medical Center College of Medicine"},
  {name:"University of Nevada, Reno School of Medicine"},
  {name:"University of Nevada, Las Vegas Kirk Kerkorian School of Medicine"},
  {name:"Roseman University College of Medicine"},
  {name:"Geisel School of Medicine at Dartmouth"},
  {name:"Cooper Medical School of Rowan University"},
  {name:"Hackensack Meridian School of Medicine"},
  {name:"Rutgers New Jersey Medical School"},
  {name:"Rutgers Robert Wood Johnson Medical School"},
  {name:"University of New Mexico School of Medicine"},
  {name:"Albany Medical College"},
  {name:"University at Buffalo Jacobs School of Medicine and Biomedical Sciences"},
  {name:"City University of New York School of Medicine"},
  {name:"SUNY Downstate College of Medicine"},
  {name:"Columbia University Vagelos College of Physicians and Surgeons"},
  {name:"Weill Cornell Medical College"},
  {name:"Albert Einstein College of Medicine"},
  {name:"Icahn School of Medicine at Mount Sinai"},
  {name:"New York University Grossman School of Medicine"},
  {name:"New York University Grossman Long Island School of Medicine"},
  {name:"New York Medical College"},
  {name:"Stony Brook University Renaissance School of Medicine"},
  {name:"University of Rochester School of Medicine & Dentistry"},
  {name:"SUNY Upstate Medical University Norton College of Medicine"},
  {name:"Zucker School of Medicine at Hofstra/Northwell"},
  {name:"Duke University School of Medicine"},
  {name:"East Carolina University Brody School of Medicine"},
  {name:"University of North Carolina School of Medicine"},
  {name:"Wake Forest School of Medicine", campuses:["Winston-Salem, NC","Charlotte, NC"]},
  {name:"University of North Dakota School of Medicine and Health Sciences"},
  {name:"Case Western Reserve University School of Medicine"},
  {name:"University of Cincinnati College of Medicine"},
  {name:"Northeast Ohio Medical University"},
  {name:"Ohio State University College of Medicine"},
  {name:"University of Toledo College of Medicine and Life Sciences"},
  {name:"Wright State University Boonshoft School of Medicine"},
  {name:"University of Oklahoma College of Medicine"},
  {name:"Oregon Health & Science University School of Medicine"},
  {name:"Drexel University College of Medicine"},
  {name:"Geisinger Commonwealth School of Medicine"},
  {name:"Thomas Jefferson University Sidney Kimmel Medical College"},
  {name:"Penn State College of Medicine"},
  {name:"University of Pennsylvania Perelman School of Medicine"},
  {name:"University of Pittsburgh School of Medicine"},
  {name:"Temple University Lewis Katz School of Medicine"},
  {name:"Universidad Central del Caribe School of Medicine"},
  {name:"Ponce Health Sciences University School of Medicine"},
  {name:"University of Puerto Rico School of Medicine"},
  {name:"San Juan Bautista School of Medicine"},
  {name:"Brown University Alpert Medical School"},
  {name:"Medical University of South Carolina"},
  {name:"University of South Carolina School of Medicine Columbia"},
  {name:"University of South Carolina School of Medicine Greenville"},
  {name:"University of South Dakota Sanford School of Medicine"},
  {name:"East Tennessee State University James H. Quillen College of Medicine"},
  {name:"Meharry Medical College"},
  {name:"Belmont University Thomas F. Frist, Jr. College of Medicine"},
  {name:"University of Tennessee College of Medicine"},
  {name:"Vanderbilt University School of Medicine"},
  {name:"Baylor College of Medicine"},
  {name:"University of Houston Tilman J. Fertitta Family College of Medicine"},
  {name:"McGovern Medical School at UTHealth Houston"},
  {name:"Texas Christian University Anne Burnett Marion School of Medicine"},
  {name:"Texas A&M University College of Medicine"},
  {name:"Texas Tech University Health Sciences Center School of Medicine", campuses:["Lubbock, TX","Amarillo, TX","Odessa, TX"]},
  {name:"University of Texas at Tyler School of Medicine"},
  {name:"Texas Tech University Health Sciences Center El Paso Paul L. Foster School of Medicine"},
  {name:"University of Texas at Austin Dell Medical School"},
  {name:"University of Texas Medical Branch"},
  {name:"University of Texas Rio Grande Valley School of Medicine"},
  {name:"UT Health San Antonio Long School of Medicine"},
  {name:"University of Texas Southwestern Medical Center"},
  {name:"University of Utah School of Medicine"},
  {name:"University of Vermont Larner College of Medicine"},
  {name:"Eastern Virginia Medical School at Old Dominion University"},
  {name:"University of Virginia School of Medicine"},
  {name:"Virginia Commonwealth University School of Medicine"},
  {name:"Virginia Tech Carilion School of Medicine"},
  {name:"University of Washington School of Medicine"},
  {name:"Washington State University Elson S. Floyd College of Medicine"},
  {name:"Marshall University Joan C. Edwards School of Medicine"},
  {name:"West Virginia University School of Medicine"},
  {name:"Medical College of Wisconsin"},
  {name:"University of Wisconsin School of Medicine and Public Health"},
  // ── DO (COCA) ──
  {name:"Alabama College of Osteopathic Medicine"},
  {name:"A.T. Still University School of Osteopathic Medicine in Arizona (Mesa)"},
  {name:"A.T. Still University Kirksville College of Osteopathic Medicine"},
  {name:"Midwestern University Arizona College of Osteopathic Medicine"},
  {name:"Midwestern University Chicago College of Osteopathic Medicine"},
  {name:"Arkansas College of Osteopathic Medicine"},
  {name:"California Health Sciences University College of Osteopathic Medicine"},
  {name:"Touro University California College of Osteopathic Medicine"},
  {name:"Touro University Nevada College of Osteopathic Medicine"},
  {name:"Touro University Montana College of Osteopathic Medicine"},
  {name:"Touro College of Osteopathic Medicine", campuses:["New York City, NY","Middletown, NY","Great Falls, MT"]},
  {name:"Western University of Health Sciences College of Osteopathic Medicine of the Pacific", campuses:["Pomona, CA","Lebanon, OR"]},
  {name:"Rocky Vista University College of Osteopathic Medicine", campuses:["Parker, CO","Ivins, UT","Billings, MT"]},
  {name:"Nova Southeastern University Dr. Kiran C. Patel College of Osteopathic Medicine", campuses:["Fort Lauderdale, FL","Clearwater, FL"]},
  {name:"Orlando College of Osteopathic Medicine"},
  {name:"Idaho College of Osteopathic Medicine"},
  {name:"Illinois College of Osteopathic Medicine"},
  {name:"Marian University College of Osteopathic Medicine"},
  {name:"Des Moines University College of Osteopathic Medicine"},
  {name:"Kansas Health Science Center–Kansas College of Osteopathic Medicine"},
  {name:"University of Pikeville Kentucky College of Osteopathic Medicine"},
  {name:"University of New England College of Osteopathic Medicine"},
  {name:"Meritus School of Osteopathic Medicine"},
  {name:"Michigan State University College of Osteopathic Medicine", campuses:["East Lansing, MI","Clinton Township, MI","Detroit, MI"]},
  {name:"William Carey University College of Osteopathic Medicine"},
  {name:"Kansas City University College of Osteopathic Medicine", campuses:["Kansas City, MO","Joplin, MO"]},
  {name:"Rowan-Virtua School of Osteopathic Medicine"},
  {name:"Burrell College of Osteopathic Medicine", campuses:["Las Cruces, NM","Melbourne, FL"]},
  {name:"D'Youville University College of Osteopathic Medicine"},
  {name:"New York Institute of Technology College of Osteopathic Medicine", campuses:["Old Westbury, NY","Jonesboro, AR"]},
  {name:"Campbell University Jerry M. Wallace School of Osteopathic Medicine"},
  {name:"Ohio University Heritage College of Osteopathic Medicine", campuses:["Athens, OH","Dublin, OH","Cleveland, OH"]},
  {name:"Oklahoma State University College of Osteopathic Medicine", campuses:["Tulsa, OK","Tahlequah, OK"]},
  {name:"Lake Erie College of Osteopathic Medicine (LECOM)", campuses:["Erie, PA","Greensburg, PA","Elmira, NY","Bradenton, FL","Jacksonville, FL"]},
  {name:"Philadelphia College of Osteopathic Medicine (PCOM)", campuses:["Philadelphia, PA","Suwanee, GA","Moultrie, GA"]},
  {name:"Duquesne University College of Osteopathic Medicine"},
  {name:"Edward Via College of Osteopathic Medicine (VCOM)", campuses:["Blacksburg, VA","Spartanburg, SC","Auburn, AL","Monroe, LA","Bluefield, VA"]},
  {name:"Lincoln Memorial University DeBusk College of Osteopathic Medicine", campuses:["Harrogate, TN","Knoxville, TN"]},
  {name:"Baptist Health Sciences University College of Osteopathic Medicine"},
  {name:"Sam Houston State University College of Osteopathic Medicine"},
  {name:"University of the Incarnate Word School of Osteopathic Medicine"},
  {name:"University of North Texas Health Science Center Texas College of Osteopathic Medicine"},
  {name:"Noorda College of Osteopathic Medicine"},
  {name:"Liberty University College of Osteopathic Medicine"},
  {name:"Pacific Northwest University of Health Sciences College of Osteopathic Medicine"},
  {name:"West Virginia School of Osteopathic Medicine"},
];

// Degree is derivable from the school name — every COCA school says "Osteopathic"; no LCME school does.
export const degreeForSchool = name => /osteopathic/i.test(name||"") ? "DO" : "MD";
// DO dual-degree programs are rare, so they're gated to a curated set (matched by name prefix —
// the stored school may carry a "— Campus" suffix). "Other" + free-text always remain available so an
// incomplete list never blocks onboarding. Expand as more DO/PhD & DO-dual programs are confirmed.
export const DO_DUAL = {
  "Michigan State University College of Osteopathic Medicine": ["phd","masters"],
  "Rowan-Virtua School of Osteopathic Medicine": ["phd","masters"],
  "New York Institute of Technology College of Osteopathic Medicine": ["phd","masters"],
  "Nova Southeastern University Dr. Kiran C. Patel College of Osteopathic Medicine": ["phd","masters"],
  "Ohio University Heritage College of Osteopathic Medicine": ["phd","masters"],
  "University of North Texas Health Science Center Texas College of Osteopathic Medicine": ["phd","masters"],
  "Philadelphia College of Osteopathic Medicine (PCOM)": ["masters"],
  "A.T. Still University Kirksville College of Osteopathic Medicine": ["masters"],
  "Des Moines University College of Osteopathic Medicine": ["masters"],
  "Western University of Health Sciences College of Osteopathic Medicine of the Pacific": ["masters"],
};
// Which dual tracks (phd/masters) to offer for a school string: MD → both for everyone; DO → curated only.
export const dualOptionsForSchool = name => {
  if(degreeForSchool(name)==="MD") return ["phd","masters"];
  const key = Object.keys(DO_DUAL).find(k => (name||"").startsWith(k));
  return key ? DO_DUAL[key] : [];
};

// Settings → edit program track (dual degree + PhD/Master's field & institution) any time.
// Degree is derived from the school (read-only here). Does NOT regenerate years — year count
